### ISSUE TITLE
Rampur?

### ISSUE THREAD

**Issue by jawwadzafar** [AbdulBsit/react-carousel#1]
Are you from Rampur bro?
Wanna collab?

**Comment by AbdulBsit** [comment]
Yes, from Rampur, sure will collaborate, but this repo is clone of https://github.com/brainhubeu/react-carousel, i was having issue in build so merged the fix from https://github.com/brainhubeu/react-carousel/issues/633 in this.

**Comment by jawwadzafar** [comment]
I commented on most recently active repo.

**Comment by AbdulBsit** [comment]
yes no problems at all, will contribute on your respos soon, or can start a new
